# Clase 2
# NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]) #Crear arreglo 
#Recibe una lista o tupla y puede ser anidada
print(arr)

print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


### Crear arreglos de varias dimensiones

In [3]:
#Dimensión 2 - Número
cero = np.array(42) 

#Dimensión 1 - Lista
uno = np.array([1,2,3,4,5])

#Dimesión 2 - Lista anidada
dos = np.array([[1,2,3],[4,5,6]])
#print(dos)

#Dimensión 3 - Lista de listas anidadas
tres = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tres)

#Imprimir dimensiones
print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

#Dimenssión n=5
cinco = np.array([1,2,3,4],ndmin=5)
print(cinco)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
0
1
2
3
[[[[[1 2 3 4]]]]]


### Localizar elementos en los arrays y un rango de datos

In [4]:
print(uno[0])
print(dos[1:])      #Si no pongo la coma me pondrá las dos listas
print(tres[0,1,:])

print(tres[1,1,2])

1
[[4 5 6]]
[4 5 6]
12


In [5]:
print(uno[1:4])   #El primero se incluye y el segundo se excluye
print(uno[1:])    #Hasta el final, desde el número que colocamos
print(uno[:4])    #Desde el principio, hasta el elemento menor antes del colocado
print(uno[-3:-1]) #Desde la menos 3 hasta uno antes de la menos 1
print(uno[1:4:2]) #PASO: Desde donde lo quiero y con que paso lo quiero, es el último parámetro

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[3 4]
[2 4]


In [6]:
print(dos[1,0:2:2])  #Esto se expande para más dimensiones: De la lista dos, ve de 0 a 2 en pasos de 2 

dosnuevo = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dos[0:2,1])

[4]
[2 5]


### Cambiar los tipos de datos, copy(), shape(), size() & reshape()

In [7]:
cadena = np.array(['lechuga','espinaca','brocoli'])
print(cadena.dtype)
#Unicof

flotante = np.array([1.2456,24.5642,654,3567])
print(flotante.dtype)
#flotante

#S, i,f

#Convertir datos, NO es la opción recomendada, por qué pueden salir cosas raras
cadena_dos=np.array([1,2,3,4],dtype='S')
print(cadena_dos.dtype)
print(cadena_dos)


<U8
float64
|S1
[b'1' b'2' b'3' b'4']


In [8]:
#Método astype() Método recomendado
entero = flotante.astype(int) #Igual se puede poner 'i'
entero = flotante.astype('i')
print(entero)

[   1   24  654 3567]


In [9]:
#Copiar copy()
copia = entero.copy()
copia[0] = 10000    #Remplazamos un elemento de la copia

print(entero)
print(copia)

[   1   24  654 3567]
[10000    24   654  3567]


In [10]:
#Conocer la forma y tamaño de los elementos
print(dosnuevo.shape)   #Forma
print(dosnuevo.size)    #Tamaño
print(tres.shape)

#Reshape() . Cambiar la forma
arreglo = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
nuevo_arreglo = arreglo.reshape(4,3)
#print(nuevo_arreglo)


#No se crea una copia, si se modifica el arreglo nuevo, se modifica el anterior
#Se debe crear una copia primero y luego modifcar esa, para no modificar el original
nuevo_arreglo[0,0] = 10000
print(arreglo)
print(nuevo_arreglo)


(3, 3)
9
(2, 2, 3)
[10000     2     3     4     5     6     7     8     9    10    11    12]
[[10000     2     3]
 [    4     5     6]
 [    7     8     9]
 [   10    11    12]]


### Iterar arreglos

In [11]:
#Iterando arreglos

arreglo = np.array([1,2,3])

for x in arreglo:
    print(x)

1
2
3


In [12]:
arreglo = np.array([[1,2],[3,4]])

#Imprime elemento por elemento
for x in arreglo:
    for y in x:
        print(y)

#Imprime las listas 
for x in arreglo:
    print(x)
    

#nditer() Iterador de n dimensiones
for x in np.nditer(arreglo):
    print(x)

1
2
3
4
[1 2]
[3 4]
1
2
3
4


## Métodos de Numpy

### hstack()     "Apilar de manera horizantal"
### vstack()     "Apilar de manera vertical"

In [13]:
#Fusionan arreglos

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
horizontal = np.hstack((arr1,arr2))
vertical = np.vstack((arr1,arr2))

print(horizontal)
print(vertical)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Random

In [14]:
from numpy import random #Aleatorio

x= random.randint(100) #Entero aleatorio
print(x)

x = random.rand() #Elemento aletorio, entre 0 y 1, si le pongo número me me pone un arreglo de ese tamaño
print(x)

x =random.randn() #Aleatorio entre -1 y 1
print(x)

x= random.rand(3,3) #Matriz 3x3 aleatoria
print(x)


x=random.randint(100,size= (3,3))
print(x)

x=random.random(2)
print(x)

42
0.9761091663559225
-1.0386339400968219
[[0.70827545 0.20273224 0.69816097]
 [0.48728888 0.02655384 0.46631544]
 [0.91107217 0.8210371  0.40842875]]
[[ 6 79  5]
 [48 14 24]
 [78 61 37]]
[0.9587071  0.51323253]


### Arrange, Linspace, Mean y más funciones de NumPy

In [15]:
#ARRANGE
arr1 = np.arange(5,16,2) #Inicio, fin, paso
print(arr1)

#LINSPACE
arr = np.linspace(10,40,num=7) #Inicio, fin y división
print(arr)

#MEDIA
media = np.mean(arr1)        #Te saca la media del arreglo
print(media)

#SUMA
suma = np.sum(x)
print(suma)


#ONES (UNOS)
arr = np.ones((3,3),dtype=int)
print(arr)


#ZEROS (CEROS)
arr = np.zeros((4,4),dtype=int)
print(arr)


#SQRT (Square root = raíz cuadrada)
arr = np.array([4,9,16])
raiz = np.sqrt(arr)
print(raiz)


#EMPTY (VACÍO) Para guardar locaciones de memoria
arr_empty = np.empty([2,2],dtype=int)
print(arr_empty)


#FULL (COMPLETO)
arr = np.full((3,3),8)
print(arr)
arr = np.full((3,3),[1,2,3])
print(arr)


#Max y min
z=[[1,2,3],[4,5,6],[7,8,9]]
maximo = np.amax(z)
minimo = np.amin(z)
print(maximo)
print(minimo)




[ 5  7  9 11 13 15]
[10. 15. 20. 25. 30. 35. 40.]
10.0
1.4719396259098785
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[2. 3. 4.]
[[-2118706590  1072606650]
 [-1616385289  1071672422]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
9
1
