# Daniel Michell Pérez Ruiz - Machine Learning I
###  Series Numpy

In [1]:
#Importamos la paquetería/modulo que vamos a utilizar
import numpy as np

1) Crea un array de sietes cuyo atributo shape sea (10,3,2)

In [2]:
#Creamos un arreglo de arange, tal que contenga 10x3x2=60 elementos. 
s =(10,3,2)
x = 7*np.ones(s)
print(x)

[[[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]

 [[7. 7.]
  [7. 7.]
  [7. 7.]]]


2) De dicho array despliega cual es su dimensión, tamaño del arreglo, tamaño un sólo elemento y tipo de dato de los elementos del arreglo.

In [3]:
print(x.shape)
print(x.size)
print(x[0,0,0].size)
print(x.dtype)

(10, 3, 2)
60
1
float64


3) Crea los siguientes vectores usando funciones de numpy

    a) Enteros del 0 al 9: 
    b) 20 valores entre el 1 y 10 espaciados uniformemente: 
    c) Enteros del 1 al 10: 
    d) Enteros del 5 al 100 con incrementos de 5 en 5: 

In [4]:
#Podemos utilizar arange o linspace 
print('a) Enteros del 0 al 9: ')
a=np.arange(0,10,1)
print(a,'\n \n')


print('b) 20 valores entre el 1 y 10 espaciados uniformemente:  ')
b=np.linspace(1,10,20)
print(b,'\n \n')

print('c) Enteros del 1 al 10:' )
c=np.linspace(1,10,10)
print(c,'\n \n')

print('d) Enteros del 5 al 100 con incrementos de 5 en 5: ')
d=np.arange(5,101,5)
print(d,'\n \n')

a) Enteros del 0 al 9: 
[0 1 2 3 4 5 6 7 8 9] 
 

b) 20 valores entre el 1 y 10 espaciados uniformemente:  
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ] 
 

c) Enteros del 1 al 10:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 
 

d) Enteros del 5 al 100 con incrementos de 5 en 5: 
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100] 
 



4) Usaremos el vector del inciso d, despliega:

       a) Todos los elementos menos el primero.
       b) Todos los elementos menos el último.
       c) Todos los elementos en sentido inverso
       d) Un elemento sí y un elemento no
       e) Elemento número 15

In [5]:
#[Inicio : fin : paso]
#a)
print(' a) Todos los elementos menos el primero. ')
print(d[1:], '\n \n')

#b)
print(' b) Todos los elementos menos el último.')
print(d[:-1], '\n \n')

#c) #Vamos de reversa, esa es la forma de ponerlo, un slice 
print('c) Todos los elementos en sentido inverso')
print(d[::-1], '\n \n')

#d) Un elemento sí y uno no
print('d) Un elemento sí y un elemento no')
print(d[::2], '\n \n')

#e)
print('e) Elemento número 15')
print(d[2])

 a) Todos los elementos menos el primero. 
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100] 
 

 b) Todos los elementos menos el último.
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 
 

c) Todos los elementos en sentido inverso
[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10   5] 
 

d) Un elemento sí y un elemento no
[ 5 15 25 35 45 55 65 75 85 95] 
 

e) Elemento número 15
15


5) Haz un vector de número aleatorios entre 0 y 1

In [6]:
aleatorio = np.random.rand(10)
print(aleatorio)

[0.51173056 0.71941017 0.80356068 0.93508616 0.25733947 0.71789783
 0.65877355 0.34826731 0.83088404 0.10444687]


In [7]:
def ajedrez(x,y):
    M = np.zeros((x,y))
    for i in range(x):
        for j in range(y):
            if i%2 == 0 and j%2 ==0 :
            #if i == j+0 or i == j+2 or i+2 == j or i == j+4 or i+4 == j: #De aquí me vino la idea jejeje
                M[i][j] = 1
            elif (i+1)%2 == 0 and (j+1)%2 == 0:
                M[i][j] = 1
            else:
                M[i][j] = 0
    return M


x = int(input('Dime el número de filas de la matriz: '))
y = int(input('Dime el número de columnas de la matriz: '))    

z = ajedrez(x,y)
print(z)

Dime el número de filas de la matriz: 5
Dime el número de columnas de la matriz: 7
[[1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]]


7) Realiza una función que encuentre el valor máximo y mínimo un arreglo 3x3 .

In [8]:
def maxmin(A):
    return np.max(A), np.min(A)

a11 = float(input('Ingresa el elemento a11 de la matriz: '))
a12 = float(input('Ingresa el elemento a12 de la matriz: '))
a13 = float(input('Ingresa el elemento a13 de la matriz: '))
a21 = float(input('Ingresa el elemento a21 de la matriz: '))
a22 = float(input('Ingresa el elemento a22 de la matriz: '))
a23 = float(input('Ingresa el elemento a23 de la matriz: '))
a31 = float(input('Ingresa el elemento a31 de la matriz: '))
a32 = float(input('Ingresa el elemento a32 de la matriz: '))
a33 = float(input('Ingresa el elemento a33 de la matriz: '))
A= np.array([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
print(A)
print('El valor máximo y mínimo de la matriz es: ', maxmin(A))    


Ingresa el elemento a11 de la matriz: 1
Ingresa el elemento a12 de la matriz: 2
Ingresa el elemento a13 de la matriz: 3
Ingresa el elemento a21 de la matriz: 4
Ingresa el elemento a22 de la matriz: 5
Ingresa el elemento a23 de la matriz: 6
Ingresa el elemento a31 de la matriz: 7
Ingresa el elemento a32 de la matriz: 8
Ingresa el elemento a33 de la matriz: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
El valor máximo y mínimo de la matriz es:  (9.0, 1.0)


9) Implementa una función que encuentre el valor máximo en un arreglo 3x3 y regrese la posición de dicho valor (r,c)

In [23]:
def valormax(A):
    return np.max(A)

a11 = float(input('Ingresa el elemento a11 de la matriz: '))
a12 = float(input('Ingresa el elemento a12 de la matriz: '))
a13 = float(input('Ingresa el elemento a13 de la matriz: '))
a21 = float(input('Ingresa el elemento a21 de la matriz: '))
a22 = float(input('Ingresa el elemento a22 de la matriz: '))
a23 = float(input('Ingresa el elemento a23 de la matriz: '))
a31 = float(input('Ingresa el elemento a31 de la matriz: '))
a32 = float(input('Ingresa el elemento a32 de la matriz: '))
a33 = float(input('Ingresa el elemento a33 de la matriz: '))
A= np.array([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
print(A)
print('El valor máximo de la matriz es: ', valormax(A),'el cual se encuentra en la posición',  (np.argmax(A)%len(A[0])+1,np.argmax(A)%len(A[0])+1) )
#print('Recuerda que python cuenta desde el cero')


Ingresa el elemento a11 de la matriz: 1
Ingresa el elemento a12 de la matriz: 2
Ingresa el elemento a13 de la matriz: 3
Ingresa el elemento a21 de la matriz: 4
Ingresa el elemento a22 de la matriz: 5
Ingresa el elemento a23 de la matriz: 6
Ingresa el elemento a31 de la matriz: 7
Ingresa el elemento a32 de la matriz: 8
Ingresa el elemento a33 de la matriz: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
El valor máximo de la matriz es:  9.0 el cual se encuentra en la posición (3, 3)


11) Haz una función que reciba dos vectores y realice el producto cruz de ellos.

In [10]:
#El producto cruz se define para vectores de dimensionalidad (3,1), donde como resultado obtenemos otro vector de la misma dimensión
def cruz(A,B):
    return np.cross(A,B)

a1 = float(input('Ingresa el primer elemento de la matriz A: '))
a2 = float(input('Ingresa el segundo elemento de la matriz A: '))
a3 = float(input('Ingresa el tercer elemento de la matriz A: '))
b1 = float(input('Ingresa el primer elemento de la matriz B: '))
b2 = float(input('Ingresa el segundo elemento de la matriz B: '))
b3 = float(input('Ingresa el tercer elemento de la matriz B: '))
A= np.array([a1,a2,a3])
B= np.array([b1,b2,b3])

print('El producto cruz entre los vectores es: ', cruz(A,B))

Ingresa el primer elemento de la matriz A: 1
Ingresa el segundo elemento de la matriz A: 2
Ingresa el tercer elemento de la matriz A: 3
Ingresa el primer elemento de la matriz B: 4
Ingresa el segundo elemento de la matriz B: 5
Ingresa el tercer elemento de la matriz B: 6
El producto cruz entre los vectores es:  [-3.  6. -3.]


12) Realiza otro vector que sea un paso por valor de un vector y comprueba que no es un paso por referencia. Explica cuál es la diferencia.

In [11]:
#Vector por valor
#Iniciamos el vector x y se la pasamos a funcion(). Dentro de la función hacemos que la variable valga un vector cero
#Dado que Python trata a los int como pasados por valor, dentro de la función se crea una copia local de x, 
#por lo que la variable original no es modificada.

x = np.array([10,20,30])
def funcion(entrada):
    entrada = np.array([0,0,0])
funcion(x)

print(x) 

[10 20 30]


13) Realiza una función que reciba una matriz un número n y genere una matriz identidad de nxn

NOTA: No se puede usar la función identity de python, debe ser desde scratch


In [12]:
 def identidad(n):
    #Creamos una matriz sobre la cual se vaya iterando
    I = [[1 if i==j else 0 for j in range(n)] for i in range(n)]
    return I
            

    
n= int(input('Introduce el tamaño de la matriz identidad: '))
identidad(n)


Introduce el tamaño de la matriz identidad: 7


[[1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1]]

14) Escribe una función que reciba una matriz y regrese True sí es una matriz identidad y un False si no es así

In [13]:
def identidad():
    if  (M== np.identity(x)).all():
        return True
    else:
        return False

M = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,1,0]])
x=int(input('De que dimensión es tu matriz: '))
print('La matriz que introdujiste es: ', identidad())



De que dimensión es tu matriz: 4
La matriz que introdujiste es:  False


In [24]:
M = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
x=int(input('De que dimensión es tu matriz: '))
print('La matriz que introdujiste es: ', identidad())


De que dimensión es tu matriz: 4
La matriz que introdujiste es:  True


15) Teniendo los siguientes vectores:
HINT: vstack, hstack

In [15]:
vector1= np.array([1,2,3,4]) 
vector2= np.array([5,6,7,8])

print('##### Inciso a) #####')
a = vector1.reshape((2, 2))
print(a)

print('##### Inciso b) #####')
b1 = np.array([vector1,vector2])
b2 = np.vstack((b1,vector1,vector2))
print(b2)

print('##### Inciso c) #####')
c1 = np.hstack((vector1,vector1))
c2 = np.array([c1, np.hstack((vector2,vector2)) ])
c3 = np.vstack((c2,c2))
print(c3)

print('##### Inciso d) #####')
d = np.vstack((c3,c3))
print(d)

##### Inciso a) #####
[[1 2]
 [3 4]]
##### Inciso b) #####
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
##### Inciso c) #####
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]
 [1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
##### Inciso d) #####
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]
 [1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]
 [1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]
 [1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


16) Haz una función que reciba una matriz y luego que te regrese una matriz donde te de un True si el elemento es mayor que 100 y False si es menor

In [16]:
'''
A = np.array([[15, 85, 103, 444, 150, 200, 35, 47],
              [532, 476, 0, 1011, 50, 674, 5, 999],
              [985, 7, 99, 101, 1, 58, 300, 78],
              [750, 649, 86, 8, 505, 41, 745, 187]])
M = []
for i in A:
    for j in i:
        if j >= 100:
            x = True
            M.append(x)
        else:
            x = False
            M.append(x)

#cien(A)

y = int(input('Cuántos renglones tiene tu matriz: '))
z = int(input('Cuántas columnas tiene tu matriz: '))
#MatrizVerdad()
#print(M)
Mnew = np.array([M])
Mnew2 = np.reshape(Mnew,(y,z))
print(Mnew2)
'''

"\nA = np.array([[15, 85, 103, 444, 150, 200, 35, 47],\n              [532, 476, 0, 1011, 50, 674, 5, 999],\n              [985, 7, 99, 101, 1, 58, 300, 78],\n              [750, 649, 86, 8, 505, 41, 745, 187]])\nM = []\nfor i in A:\n    for j in i:\n        if j >= 100:\n            x = True\n            M.append(x)\n        else:\n            x = False\n            M.append(x)\n\n#cien(A)\n\ny = int(input('Cuántos renglones tiene tu matriz: '))\nz = int(input('Cuántas columnas tiene tu matriz: '))\n#MatrizVerdad()\n#print(M)\nMnew = np.array([M])\nMnew2 = np.reshape(Mnew,(y,z))\nprint(Mnew2)\n"

In [17]:

def cien(A):
    global N
    N = []
    for i in A:
        for j in i:
            if j >= 100:
                N.append(True)
            else:
                N.append(False)


A = np.array([[15, 85, 103, 444, 150, 200, 35, 47],
              [532, 476, 0, 1011, 50, 674, 5, 999],
              [985, 7, 99, 101, 1, 58, 300, 78],
              [750, 649, 86, 8, 505, 41, 745, 187]])

 


#MatrizVerdad()
def cienreshape(x,y):
    return np.reshape(N,(x,y))

#Mnew2 = np.reshape(Mnew,(x,y))
x = int(input('Cuántos renglones tiene tu matriz: '))
y = int(input('Cuántas columnas tiene tu matriz: '))
cien(A)
Nnew= cienreshape(x,y)
print(Nnew)


Cuántos renglones tiene tu matriz: 4
Cuántas columnas tiene tu matriz: 8
[[False False  True  True  True  True False False]
 [ True  True False  True False  True False  True]
 [ True False False  True False False  True False]
 [ True  True False False  True False  True  True]]


17) Realiza una función que reciba dos arreglos de una dimensión y regrese un arreglo con los valores que no tienen en común los dos arreglos

In [18]:
#Se puede realizar asignando o no los valores a la función, a continuación se ejemplifican ambas
def comun(x1,x2):
    return set(x1).symmetric_difference(x2)



#x1 = np.array([2,6,2,4,6,7,2,31,11,2,4,6,7,24])
#x2 = np.array([3,2,4,5,6,5,7,8,3,1,4,7,4,10])

x1= np.array([3,6,9,12,15])
x2= np.array([2,4,6,8,10,12])
x = comun(x1,x2)
y = list(x)
z = np.array(y)
print(z)
#print(type(y))

[ 2  3  4  8  9 10 15]


In [19]:
def comun():
    return set(x1).symmetric_difference(x2)



#x1 = np.array([2,6,2,4,6,7,2,31,11,2,4,6,7,24])
#x2 = np.array([3,2,4,5,6,5,7,8,3,1,4,7,4,10])
x1= np.array([3,6,9,12,15])
x2= np.array([2,4,6,8,10,12])
x = comun()
y = list(x)
z = np.array(y)
print(z)
#print(type(y))


[ 2  3  4  8  9 10 15]


18) Escribe una función que reciba un vector y regresé el promedio de todos los valores que hay en él.

In [20]:
def promedio(A):
    return np.mean(A)

A =np.array([1,2,4,6])
promedio(A)

3.25

19) Implementa una función que reciba un vector con valores entre el 1 y 10 que pueden o no estar repetidos y que te regrese un vector con los valores únicos (no repetidos) de el vector recibido.

In [21]:
'''
valores = [1,2,3,4,5,1,2,3,6,7,8,9,10,10,9,8]
repetido = []
unico = []
 
for x in valores:
    if x not in unico:
        unico.append(x)
    else:
        if x not in repetido:
            repetido.append(x)
 
print('La lista con únicos es: ',unico)
print('La lista con repetidos es: ',repetido)

#unico_array = np.array([unico])
#repetido_array = np.array([repetido])
#unico_array.difference(repetido_array)
unico_verdadero = list(set(unico).difference(repetido))
#unico_verdadero =np.array([ set(unico).difference(repetido)])
unico_verdadero_new = np.array(unico_verdadero)
print(unico_verdadero_new)


#print('La lista nueva es: ', unico)       
#array = np.array(unico)
#print(array)
#print(repetido)
'''

"\nvalores = [1,2,3,4,5,1,2,3,6,7,8,9,10,10,9,8]\nrepetido = []\nunico = []\n \nfor x in valores:\n    if x not in unico:\n        unico.append(x)\n    else:\n        if x not in repetido:\n            repetido.append(x)\n \nprint('La lista con únicos es: ',unico)\nprint('La lista con repetidos es: ',repetido)\n\n#unico_array = np.array([unico])\n#repetido_array = np.array([repetido])\n#unico_array.difference(repetido_array)\nunico_verdadero = list(set(unico).difference(repetido))\n#unico_verdadero =np.array([ set(unico).difference(repetido)])\nunico_verdadero_new = np.array(unico_verdadero)\nprint(unico_verdadero_new)\n\n\n#print('La lista nueva es: ', unico)       \n#array = np.array(unico)\n#print(array)\n#print(repetido)\n"

In [25]:
def Unico():
  global unico
  unico = []
  global repetido 
  repetido= []
  for x in valores:
    if x not in unico:
      unico.append(x)
      #print(unico)
    else:
      if x not in repetido:
        repetido.append(x)


#valores = [1,2,3,4,5,1,2,3,6,7,8,9,10,10,9,8]
valores =[1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 7, 8, 8, 9, 9, 9, 10, 10]
Unico()
unico_verdadero = list(set(unico).difference(repetido))
#unico_verdadero_new = np.array(unico_verdadero)

print(unico_verdadero)

[1, 4, 7]


20) En esta opción eres libre de poner cualquier función que use elementos y funciones de la librería numpy. Debes comentar que es lo que hace.